export interface ItemsI {
    categoria: string,
    descripcion: string,
    codigobarras?: string,
    cantidad: string,
    precio: string,
    subtotal12: string,
    subtotal0: string,
    notaVenta: string,
    iva12: string,
    iva0: string,
    total: string,
    lote: string,
    numerolote?: string,
    nombre_proser?: string,
    fechaelaboracion?: string,
    fechavencimiento?: string,
    iva?: string,
    descuento?: string
}