export interface RolI {
    id_sueldos: string,
    nombres: string,
    apellidos: string,
    sueldo: string,
    diastrabajados: string,
    bonostransporte: string,
    bonosalimentacion: string,
    otrosingresos: string,
    decimotercer: string,
    decimocuarto: string,
    totalingresos: string,
    iessindividual: string,
    iesspatronal: string,
    iesstotal: string,
    anticipos: string,
    prestamos_oficina: string,
    prestamo_hipotecario: string,
    prestamo_quirografario: string,
    otrosegresos: string,
    total_egresos: string,
    neto_recibir: string,
    contrato: string,
    aprobado: string,
    actafiniquito: string,
    create_at: string
}